//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTWeb10_Bai01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTiet
    {
        public int MaHoaDon { get; set; }
        public int MaSanPham { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual tblHoaDon tblHoaDon { get; set; }
        public virtual tblSanPham tblSanPham { get; set; }
    }
}
